package org.apache.jsp.WEB_002dINF.manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class transcriptprint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">   \r\n");
      out.write("    <title></title>\t   \r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("js/ligerUI/skins/Aqua/css/ligerui-all.css\" rel=\"stylesheet\"type=\"text/css\" />\t\r\n");
      out.write("\t<link href=\"");
      out.print(basePath );
      out.write("js/ligerUI/skins/Gray/css/all.css\" rel=\"stylesheet\" type=\"text/css\"/>\t\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-validation/jquery.validate.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/json2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-validation/jquery.metadata.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-validation/messages_cn.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"js/jquery/jquery-1.3.2.min.js\"type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"js/ligerUI/core/base.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"js/ligerUI/ligerui.all.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery/jquery-1.4.4.min.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.jqprint-0.3.js\" ></script>\r\n");
      out.write("\t<!-- <script type=\"text/javascript\" src=\"js/semester.js\" ></script>  -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\t\t\t\r\n");
      out.write("\tvar nowDate = new Date();\r\n");
      out.write("\tvar nowYear = nowDate.getFullYear();\r\n");
      out.write("\tvar lastYear = parseInt(nowYear)-1;\r\n");
      out.write("\tvar before = parseInt(lastYear)-1;\r\n");
      out.write("\tvar nextYear = parseInt(nowYear)+1;\r\n");
      out.write("\tvar nowuptext = lastYear+\"-\"+nowYear+\"学年第一学期\";//2014-2015\r\n");
      out.write("\tvar nowupvalue = lastYear+\"01\";\r\n");
      out.write("\tvar nowdowntext = lastYear+\"-\"+nowYear + \"学年第二学期\";\r\n");
      out.write("\tvar nowdownvalue = nowYear+\"02\";\r\n");
      out.write("\tvar lastuptext = before+\"-\"+lastYear+\"学年第一学期\";\r\n");
      out.write("\tvar lastupvalue = before+\"01\";\r\n");
      out.write("\tvar lastdowntext = before+\"-\"+lastYear+\"学年第二学期\";\r\n");
      out.write("\tvar lastdownvalue = lastYear+\"02\";\r\n");
      out.write("\tvar nextuptext = nowYear+\"-\"+nextYear+\"学年第一学期\";\r\n");
      out.write("\tvar nextupvalue = nowYear+\"01\";\r\n");
      out.write("\tvar nextdowntext = nowYear+\"-\"+nextYear+\"学年第二学期\";\r\n");
      out.write("\tvar nextdownvalue = nextYear+\"02\";\r\n");
      out.write("\tvar semester = document.getElementById(\"semester\");\r\n");
      out.write("\tvar objOption=document.createElement(\"OPTION\"); \r\n");
      out.write("    var objOption1=document.createElement(\"OPTION\");\r\n");
      out.write("    var objOption2=document.createElement(\"OPTION\"); \r\n");
      out.write("    var objOption3=document.createElement(\"OPTION\"); \r\n");
      out.write("    var objOption4=document.createElement(\"OPTION\"); \r\n");
      out.write("    var objOption5=document.createElement(\"OPTION\"); \r\n");
      out.write("    objOption.value=nowupvalue;   objOption.text=nowuptext;\r\n");
      out.write("    objOption1.value=nowdownvalue;  objOption1.text=nowdowntext;\r\n");
      out.write("    objOption2.value=lastupvalue;  objOption2.text=lastuptext;\r\n");
      out.write("    objOption3.value=lastdownvalue;  objOption3.text=lastdowntext;\r\n");
      out.write("    objOption4.value=nextupvalue;  objOption4.text=nextuptext;\r\n");
      out.write("    objOption5.value=nextdownvalue;  objOption5.text=nextdowntext;\r\n");
      out.write("    var month = nowDate.getMonth();\r\n");
      out.write("\tvar now;\r\n");
      out.write("\tif (month > 9) {\r\n");
      out.write("\t\tnow = nowYear + \"01\";\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tnow = nowYear + \"02\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(now==nowupvalue){\r\n");
      out.write("\t\tsemester.add(objOption2);\r\n");
      out.write("        semester.add(objOption3);\r\n");
      out.write("        semester.add(objOption);\r\n");
      out.write("        semester.options[semester.options.length-1].selected='selected';\r\n");
      out.write("        semester.add(objOption1);                \r\n");
      out.write("        semester.add(objOption4);\r\n");
      out.write("        semester.add(objOption5);        \t\t\r\n");
      out.write("\t}else if(now==nowdownvalue) {\r\n");
      out.write("\t\tsemester.add(objOption2);\r\n");
      out.write("        semester.add(objOption3);\r\n");
      out.write("        semester.add(objOption);        \r\n");
      out.write("        semester.add(objOption1); \r\n");
      out.write("        semester.options[semester.options.length-1].selected='selected';\r\n");
      out.write("        semester.add(objOption4);\r\n");
      out.write("        semester.add(objOption5);\r\n");
      out.write("\t}\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("}) \r\n");
      out.write("    var date = new Date();\r\n");
      out.write("    var nowyear = date.getFullYear();\r\n");
      out.write("    var month = date.getMonth()+1;\r\n");
      out.write("    var day = date.getDate();\r\n");
      out.write("    var nowdate = nowyear+\" 年    \"+month+\" 月   \"+day+\" 日 \";\r\n");
      out.write("    var endate = month +\"       \"+day+\" ,  \"+nowyear;\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("    document.getElementById(\"fprint\").style.display = \"none\";    \r\n");
      out.write("    document.getElementById(\"nowdate\").innerHTML=nowdate;\r\n");
      out.write("    document.getElementById(\"endate\").innerHTML=endate;\r\n");
      out.write("  })\r\n");
      out.write("  function f_search(){\r\n");
      out.write("     var semester= $(\"#semester\").val();\r\n");
      out.write("     var stuid = $(\"#stuid\").val();\r\n");
      out.write("     if(stuid.length==0){\r\n");
      out.write("        alert(\"请输入查询护照号！\");\r\n");
      out.write("     }else{\r\n");
      out.write("         $(\"span\").empty();\r\n");
      out.write("         $(\".tabletr\").empty();\r\n");
      out.write("         $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Manage_transcriptsearch.action?semChosenCourse.semester=\"+semester+\"&stu.passport=\"+stuid\r\n");
      out.write("         ,null,function(data){\r\n");
      out.write("            if(data==\"#\"){\r\n");
      out.write("                alert(\"没有查到相关成绩！\");\r\n");
      out.write("            }else{\r\n");
      out.write("                //document.getElementById(\"fprint\").style.display = \"block\";\r\n");
      out.write("                var arr = new Array();\r\n");
      out.write("                arr = data.split(\"#\");\r\n");
      out.write("                var obj = eval(arr[0]);\r\n");
      out.write("                var stu = eval(arr[1]);\r\n");
      out.write("                for(var i=0;i<stu.length;i++){\r\n");
      out.write("                   $(\"#stuname\").html(stu[i].stuname);\r\n");
      out.write("                   $(\"#classname\").html(stu[i].classname);\r\n");
      out.write("                   $(\"#engname\").html(stu[i].engname);\r\n");
      out.write("                   $(\"#nation\").html(stu[i].nation);\r\n");
      out.write("                   $(\"#startyear\").html(stu[i].startdate.substring(0,4));\r\n");
      out.write("                   $(\"#startmonth\").html(stu[i].startdate.substring(5,7));\r\n");
      out.write("                   $(\"#endyear\").html(stu[i].enddate.substring(0,4));\r\n");
      out.write("                   $(\"#endmonth\").html(stu[i].enddate.substring(5,7));\r\n");
      out.write("                   $(\"#startyear1\").html(stu[i].startdate.substring(0,4));\r\n");
      out.write("                   $(\"#startmonth1\").html(stu[i].startdate.substring(5,7));\r\n");
      out.write("                   $(\"#endyear1\").html(stu[i].enddate.substring(0,4));\r\n");
      out.write("                   $(\"#endmonth1\").html(stu[i].enddate.substring(5,7));\r\n");
      out.write("                } \r\n");
      out.write("                var table = document.getElementById(\"table2\");\r\n");
      out.write("                for(var i=0;i<obj.length;i++){ \r\n");
      out.write("                   NewRow = table.insertRow(-1);                        //添加行\r\n");
      out.write("                   newcell1= NewRow.insertCell(-1);                     //添加列\r\n");
      out.write("                   newcell2=NewRow.insertCell(-1);\r\n");
      out.write("                   newcell3=NewRow.insertCell(-1);\r\n");
      out.write("                   newcell4=NewRow.insertCell(-1);\r\n");
      out.write("                   newcell5=NewRow.insertCell(-1);\r\n");
      out.write("                   newcell6=NewRow.insertCell(-1);\r\n");
      out.write("                   newcell7=NewRow.insertCell(-1);\r\n");
      out.write("                   newcell8=NewRow.insertCell(-1);\r\n");
      out.write("                   newcell9=NewRow.insertCell(-1);\r\n");
      out.write("                   NewRow.setAttribute('class', 'tabletr');\r\n");
      out.write("                   newcell1.innerHTML = obj[i].semester;          //添加数据\r\n");
      out.write("                   newcell2.innerHTML = obj[i].coursename;\r\n");
      out.write("                   newcell3.innerHTML = obj[i].credits;\r\n");
      out.write("                   newcell4.innerHTML = obj[i].lessoncount;\r\n");
      out.write("                   newcell5.innerHTML = obj[i].attendence;\r\n");
      out.write("                   newcell6.innerHTML = obj[i].homework;\r\n");
      out.write("                   newcell7.innerHTML = obj[i].midexam;\r\n");
      out.write("                   newcell8.innerHTML = obj[i].finalexam;\r\n");
      out.write("                   newcell9.innerHTML = obj[i].summary;  \r\n");
      out.write("                } \r\n");
      out.write("               document.getElementById(\"nowdate\").innerHTML=nowdate;\r\n");
      out.write("               document.getElementById(\"endate\").innerHTML=endate;\r\n");
      out.write("           }\r\n");
      out.write("       });  \r\n");
      out.write("     }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  /* function f_print(){\r\n");
      out.write("   $(\"#content\").jqprint();\r\n");
      out.write("  } */\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#head{\r\n");
      out.write(" width: 99.2%;\r\n");
      out.write(" height:80px;\r\n");
      out.write(" margin:auto;\r\n");
      out.write(" border:4px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write(" float: left;\r\n");
      out.write(" height: 100%;\r\n");
      out.write(" width: 10%;\r\n");
      out.write(" text-aligncenter;\r\n");
      out.write(" border-right:2px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write(".search{\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write(".l-table-edit{\r\n");
      out.write(" height:80px;\r\n");
      out.write(" align:center;\r\n");
      out.write(" width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".search.l-table-edit td{\r\n");
      out.write("  border-bottom: 1px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write(".link{\r\n");
      out.write("width:180px;height:25px;background: #fefefe;border: 1px solid #bbb;font-size: 14px;color: #333;border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write(".l-button{\r\n");
      out.write(" width:70px;float:left; margin:15px 180px 5px ;\r\n");
      out.write(" border-radiux:5px;\r\n");
      out.write("}\r\n");
      out.write("#content{\r\n");
      out.write("  border-top: 2px solid #d5d5d5 ; \r\n");
      out.write("  height:auto;  \r\n");
      out.write("  margin-top: 40px;\r\n");
      out.write("  margin:auto;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("}\r\n");
      out.write("#table1{\r\n");
      out.write("width: 85%;margin:auto;border:1px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write("#table1 td{\r\n");
      out.write("border:1px solid #c6c6c6 ;\r\n");
      out.write("margin:auto;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#score{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("#table2{\r\n");
      out.write("margin-top:20px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("width: 85%;margin:auto;border:1px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write("#table2 td{\r\n");
      out.write("border:1px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write("#note{\r\n");
      out.write("  width:85%;\r\n");
      out.write("  margin:auto;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("#time{\r\n");
      out.write(" float: left;\r\n");
      out.write(" width:35%;\r\n");
      out.write(" margin:auto;\r\n");
      out.write(" margin-left:100px;\r\n");
      out.write(" margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("#school{\r\n");
      out.write("float: left;\r\n");
      out.write(" width:35%;\r\n");
      out.write(" margin:auto;\r\n");
      out.write(" margin-left:150px;\r\n");
      out.write(" margin-top: 50px;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"head\">\r\n");
      out.write("\t      <div class=\"title\" ><br><br><div align=\"center\"><font face=\"微软雅黑\" color=\"#400000\" size=\"4\"><strong>条件选择</strong></font></div></div>\r\n");
      out.write("\t      <div class=\"search\" >\r\n");
      out.write("\t         <table cellpadding=\"0\" cellspacing=\"0\" class=\"l-table-edit\" width=\"100%\" >\r\n");
      out.write("\t\t\t  <tr>\t\t\t\t\r\n");
      out.write("\t\t\t    <td align=\"right\" class=\"l-table-edit-td\" width=\"100px\" >&nbsp;&nbsp;专业:&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t  <input id=\"major\" class=\"link\" name=\"major\" value=\"汉语言\" disabled=\"disabled\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t");
      out.write("\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t   <td align=\"right\" class=\"l-table-edit-td\">&nbsp;&nbsp;&nbsp;开课学期: <br></td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t   <select id=\"semester\" name=\"semester\" class=\"link\" >\r\n");
      out.write("\t\t\t\t     <option></option>\r\n");
      out.write("\t\t\t\t   </select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\" class=\"l-table-edit-td\">&nbsp;&nbsp;学生护照号:<font color=\"#ff0000\">*</font> <br></td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t  <input id=\"stuid\" class=\"link\" name=\"stuid\" value=\"\"  />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<a class=\"l-button\" onclick=\"f_search()\"><strong>查&nbsp;&nbsp;询</strong></a>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<a class=\"l-button\" href=\"system/Manage_sendBackTranscript.action\">打印</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div id=\"content\" >\r\n");
      out.write("\t<div style=\"width:80%;margin-right: 50px;margin-top:10px;\"align=\"right\" >编号No：</div>\r\n");
      out.write("\t   <table id=\"table1\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" >\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t        <td colspan=\"2\" >&nbsp;  姓名：<span id=\"stuname\" ></span><br>&nbsp;Name:<span id=\"engname\" ></span></td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t        <td style=\"width:50%;\" >&nbsp; 班级：<span id=\"classname\" ></span><br>&nbsp; Class:</td>\r\n");
      out.write("\t        <td>&nbsp;国籍：<span id=\"nation\" ></span><br>&nbsp;Nationality:</td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t        <td colspan=\"2\" >&nbsp;学习期限:自 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"startyear\" ></span>&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"startmonth\" ></span>&nbsp;&nbsp;&nbsp;&nbsp;月到&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"endyear\" ></span>&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"endmonth\" ></span>&nbsp;&nbsp;&nbsp;&nbsp;月<br>\r\n");
      out.write("                             &nbsp;Duration of Study: From&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"startmonth1\" ></span>&nbsp;&nbsp;&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"startyear1\" ></span> &nbsp;&nbsp;&nbsp;&nbsp; to &nbsp;&nbsp;&nbsp;&nbsp;<span id=\"endmonth1\" ></span>&nbsp;&nbsp;&nbsp;&nbsp;, &nbsp;&nbsp;&nbsp;&nbsp;<span id=\"endyear1\" ></span>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t   </table> \r\n");
      out.write("\t   <div id=\"score\" ><br><br>\r\n");
      out.write("\t     <table id=\"table2\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" >\r\n");
      out.write("\t   <tr >\r\n");
      out.write("\t        <td rowspan=\"2\" >开课学期<br>Term</td>\r\n");
      out.write("\t        <td rowspan=\"2\">课程<br>Subject</td>\r\n");
      out.write("\t        <td rowspan=\"2\">学分<br>（Credit(s)）</td>\r\n");
      out.write("\t        <td rowspan=\"2\">总课时<br>Teaching Hours</td>\r\n");
      out.write("\t        <td colspan=\"5\">成绩<br>Score</td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t     <tr >\r\n");
      out.write("\t        <td>出勤</td>\r\n");
      out.write("\t        <td>作业</td>\r\n");
      out.write("\t        <td>期中</td>\r\n");
      out.write("\t        <td>期末</td>\r\n");
      out.write("\t        <td>总评</td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t   </table> \r\n");
      out.write("\t   </div>\t\r\n");
      out.write("\t   <div id=\"note\" >\r\n");
      out.write("<strong>\t     <font size=\"4\"><br><br>注Note：</font></strong>\r\n");
      out.write("<br><p>&nbsp;<font size=\"3\"> </font><font size=\"3\">1.成绩采取综合测评方式, 满分为100分，其中出勤占10分, 作业占20分, 期中考试占30分，期末考试占40分。总评成绩达到60分为及格，可以获得该门课程的学分。 </font></p><p><font size=\"3\"><font size=\"2\">&nbsp; 2.出勤：Attendance； 作业：Homework； 期中：Middle Examination； 期末：Final Examination；总评：Total Score；</font>  \r\n");
      out.write("\t   </font></p></div>  \r\n");
      out.write("\t   <div id=\"time\">&nbsp; \r\n");
      out.write("\t     <font size=\"4\">日期：<span id=\"nowdate\" ></span><br>\r\n");
      out.write("\t     &nbsp;Date:&nbsp;&nbsp;<span id=\"endate\" ></span>\r\n");
      out.write("\t   </div> \r\n");
      out.write("\t   <div id=\"school\" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;\r\n");
      out.write("<font size=\"4\"><strong>\t    <font face=\"黑体\">天津工业大学国际教育学院 </font></strong></font><font face=\"黑体\"><strong><br>&nbsp;<font size=\"4\">School of International Education\r\n");
      out.write("<br>&nbsp;&nbsp; Tianjin Polytechnic University \r\n");
      out.write("</font></strong></font><strong>\t   </strong></div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
