package org.apache.jsp.WEB_002dINF.course;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class courseclassstulist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>班级列表</title>\r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("js/ligerUI/skins/Aqua/css/ligerui-all.css\" rel=\"stylesheet\"type=\"text/css\" />\t\r\n");
      out.write("\t<link href=\"");
      out.print(basePath );
      out.write("js/ligerUI/skins/Gray/css/all.css\" rel=\"stylesheet\" type=\"text/css\"/>\t\r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("css/date.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("js/json2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("js/jquery/jquery-1.3.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath );
      out.write("js/ligerUI/core/base.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath );
      out.write("js/ligerUI/ligerui.all.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.date_input.pack.js\" type=\"text/javascript\"></script>\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("     $(function(){\r\n");
      out.write("\t     $('.date_picker').date_input();\r\n");
      out.write("\t })\r\n");
      out.write("    var ClassData = { \r\n");
      out.write("\tRows: [");
String s = (String) request.getAttribute("classlist");
      out.write(' ');
      out.print(s);
      out.write("]};\r\n");
      out.write("    var ClassList = ClassData.Rows;\r\n");
      out.write("    var sexData = [{ Sex: 1, text: '男' }, { Sex: 2, text: '女'}];\r\n");
      out.write("    var ClassStuData = {Rows: [\r\n");
      out.write("\t\t");
String  ss= (String) request.getAttribute("studentlist");
      out.write("\r\n");
      out.write("\t\t");
      out.print(ss);
      out.write("\r\n");
      out.write("\t\t ]};\t\r\n");
      out.write("   $(f_initGrid);\r\n");
      out.write("\tvar manager, g;\r\n");
      out.write("\tfunction f_initGrid() {\r\n");
      out.write("\t\tg = manager = $(\"#maingrid\").ligerGrid(\r\n");
      out.write("\t\t\t{columns : [\r\n");
      out.write("\t\t\t{   display : '序号',  name : 'id',     width : 40,  type : 'int',hide:true\r\n");
      out.write("\t\t\t},{display : '护照号', name : 'passport', minWidth : 100,  editor:{type:'text'}\t}\r\n");
      out.write("\t\t\t, {display : '学号', name : 'stuid',  minWidth : 120, editor: { type: 'text'}\r\n");
      out.write("\t\t\t/* }, {display : '英文名', name : 'firstname',minWidth : 100, editor: { type: 'text'}\r\n");
      out.write("\t\t\t}, {display : '英文姓', name : 'lastname',minWidth : 100, editor: { type: 'text'} */\r\n");
      out.write("\t\t\t}, {display : '姓名', name : 'stuname',minWidth : 80, editor: { type: 'text'}\t\t\t\r\n");
      out.write("\t\t\t}/*  ,{ display: '班级',  name: 'classid', minWidth: 100, isSort: false,\r\n");
      out.write("            editor: { type: 'select', data: ClassList, valueColumnName: 'Classid', displayColumnName: 'Classname' }, \r\n");
      out.write("                  render: function (item)\r\n");
      out.write("                    {for (var i = 0; i < ClassList.length; i++)\r\n");
      out.write("                        { if (ClassList[i]['Classid'] == item.classid)\r\n");
      out.write("                                return ClassList[i]['Classname'];\r\n");
      out.write("                        }\r\n");
      out.write("                        return item.Classname;\r\n");
      out.write("                    }\r\n");
      out.write("                } */\r\n");
      out.write("             ,{display : '电话', name : 'telephone', minWidth : 100,  editor:{type:'text'} }\r\n");
      out.write("             ],\r\n");
      out.write("\t\t\t\t\tonSelectRow : function(rowdata, rowindex) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#txtrowindex\").val(rowindex);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tcheckbox:true,\r\n");
      out.write("\t\t\t\t\tenabledEdit : true,\r\n");
      out.write("\t\t\t\t\tclickToEdit : false,\r\n");
      out.write("\t\t\t\t\tisScroll : false,\r\n");
      out.write("\t\t\t\t\trownumbers:true, \r\n");
      out.write("\t\t\t\t\tpageSize:30,\r\n");
      out.write("\t\t\t\t\t//url :'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Stu_attendencestulist.action',\r\n");
      out.write("\t\t\t\t\tdata:ClassStuData,\r\n");
      out.write("\t\t\t\t\twidth : '100%'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("\tfunction attendence(){\r\n");
      out.write("\t  var row = manager.getSelectedRow();\r\n");
      out.write("\t\tif (!row) {\r\n");
      out.write("\t\t\talert('请选择至少一名学生！');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("      var str = \"\";\r\n");
      out.write("      var rows = manager.getCheckedRows();\r\n");
      out.write("      $(rows).each(function ()\r\n");
      out.write("       {\r\n");
      out.write("         str += this.passport + \",\";\r\n");
      out.write("       });\r\n");
      out.write("      var str1=\"0\";\r\n");
      out.write("      if((document.all.date.value ==\"\")){\r\n");
      out.write("\t      $(\"#result\").html(\"日期不能为空！\");\r\n");
      out.write("\t   $(\"#result\").show();\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t      $(\"#result\").hide();\r\n");
      out.write("\t      check();\r\n");
      out.write("\t      if(flg){\r\n");
      out.write("\t         $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Manage_stuattendenceadd.action?ids=\"+ str\r\n");
      out.write("\t  +\"&attendence.type=\"+str1\r\n");
      out.write("\t  +\"&attendence.date=\"+encodeURI(encodeURI($(\"#date\").val()))\r\n");
      out.write("\t  +\"&attendence.time=\"+encodeURI(encodeURI($(\"#time option:selected\").val()))\r\n");
      out.write("\t  +\"&attendence.choosencourseid=\"+encodeURI(encodeURI($(\"#courseid\").val()))\r\n");
      out.write("\t\t,null,function(){\r\n");
      out.write("\t\tmanager.deleteSelectedRow();\r\n");
      out.write("\t\talert(\"操作成功！\");\r\n");
      out.write("\t   });\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t   }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction late(){\r\n");
      out.write("\t  var row = manager.getSelectedRow();\r\n");
      out.write("\t\tif (!row) {\r\n");
      out.write("\t\t\talert('请选择至少一名学生！');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("      var str = \"\";\r\n");
      out.write("      var rows = manager.getCheckedRows();\r\n");
      out.write("      $(rows).each(function ()\r\n");
      out.write("       {\r\n");
      out.write("         str += this.passport + \",\";\r\n");
      out.write("       });\r\n");
      out.write("      var str1=\"1\";\r\n");
      out.write("      if((document.all.date.value ==\"\")){\r\n");
      out.write("\t      $(\"#result\").html(\"日期不能为空！\");\r\n");
      out.write("\t   $(\"#result\").show();\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t      $(\"#result\").hide();\r\n");
      out.write("\t      check();\r\n");
      out.write("\t      if(flg){\r\n");
      out.write("\t      $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Manage_stuattendenceadd.action?ids=\"+ str\r\n");
      out.write("\t  +\"&attendence.type=\"+str1\r\n");
      out.write("\t  +\"&attendence.date=\"+encodeURI(encodeURI($(\"#date\").val()))\r\n");
      out.write("\t  +\"&attendence.time=\"+encodeURI(encodeURI($(\"#time option:selected\").val()))\r\n");
      out.write("\t  +\"&attendence.choosencourseid=\"+encodeURI(encodeURI($(\"#courseid\").val()))\r\n");
      out.write("\t\t,null,function(){\r\n");
      out.write("\t\tmanager.deleteSelectedRow();\r\n");
      out.write("\t\talert(\"操作成功！\");\r\n");
      out.write("\t   });\t      \r\n");
      out.write("\t      }\t      \r\n");
      out.write("\t   }\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction leaveearly(){\r\n");
      out.write("\t  var row = manager.getSelectedRow();\r\n");
      out.write("\t\tif (!row) {\r\n");
      out.write("\t\t\talert('请选择至少一名学生！');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("      var str = \"\";\r\n");
      out.write("      var rows = manager.getCheckedRows();\r\n");
      out.write("      $(rows).each(function ()\r\n");
      out.write("       {\r\n");
      out.write("         str += this.passport + \",\";\r\n");
      out.write("       });\r\n");
      out.write("      var str1=\"2\";\r\n");
      out.write("      if((document.all.date.value ==\"\")){\r\n");
      out.write("\t      $(\"#result\").html(\"日期不能为空！\");\r\n");
      out.write("\t   $(\"#result\").show();\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t      $(\"#result\").hide();\r\n");
      out.write("\t      check();\r\n");
      out.write("\t      if(flg){\r\n");
      out.write("\t        $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Manage_stuattendenceadd.action?ids=\"+ str\r\n");
      out.write("\t  +\"&attendence.type=\"+str1\r\n");
      out.write("\t  +\"&attendence.date=\"+encodeURI(encodeURI($(\"#date\").val()))\r\n");
      out.write("\t  +\"&attendence.time=\"+encodeURI(encodeURI($(\"#time option:selected\").val()))\r\n");
      out.write("\t  +\"&attendence.choosencourseid=\"+encodeURI(encodeURI($(\"#courseid\").val()))\r\n");
      out.write("\t\t,null,function(){\r\n");
      out.write("\t\tmanager.deleteSelectedRow();\r\n");
      out.write("\t\talert(\"操作成功！\");\r\n");
      out.write("\t   });\r\n");
      out.write("\t    }\t      \r\n");
      out.write("\t   }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction notarrival(){\r\n");
      out.write("\tvar row = manager.getSelectedRow();\r\n");
      out.write("\t\tif (!row) {\r\n");
      out.write("\t\t\talert('请选择至少一名学生！');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("      var str = \"\";\r\n");
      out.write("      var rows = manager.getCheckedRows();\r\n");
      out.write("      $(rows).each(function ()\r\n");
      out.write("       {\r\n");
      out.write("         str += this.passport + \",\";\r\n");
      out.write("       });\r\n");
      out.write("      var str1=\"3\";\r\n");
      out.write("      if((document.all.date.value ==\"\")){\r\n");
      out.write("\t      $(\"#result\").html(\"日期不能为空！\");\r\n");
      out.write("\t   $(\"#result\").show();\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t      $(\"#result\").hide();\r\n");
      out.write("\t      check();\r\n");
      out.write("\t      if(flg){\r\n");
      out.write("\t      $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Manage_stuattendenceadd.action?ids=\"+ str\r\n");
      out.write("\t  +\"&attendence.type=\"+str1\r\n");
      out.write("\t  +\"&attendence.date=\"+encodeURI(encodeURI($(\"#date\").val()))\r\n");
      out.write("\t  +\"&attendence.time=\"+encodeURI(encodeURI($(\"#time option:selected\").val()))\r\n");
      out.write("\t  +\"&attendence.choosencourseid=\"+encodeURI(encodeURI($(\"#courseid\").val()))\r\n");
      out.write("\t\t,null,function(){\r\n");
      out.write("\t\tmanager.deleteSelectedRow();\r\n");
      out.write("\t\talert(\"操作成功！\");\r\n");
      out.write("\t   });\r\n");
      out.write("\t      }\t      \r\n");
      out.write("\t   }\r\n");
      out.write("\t}\r\n");
      out.write("\tvar flg = false;\r\n");
      out.write("\tfunction check(){\r\n");
      out.write("\t  var date =$(\"#date\").val();\r\n");
      out.write("\t  var nowDate = new Date();\r\n");
      out.write("\t  var now = nowDate.getFullYear()+\"-\"+(parseInt(nowDate.getMonth())+1)+\"-\"+nowDate.getDate();\r\n");
      out.write("\t  var d1 = new Date(date.replace(/\\-/g, \"\\/\"));\r\n");
      out.write("\t  var d2 = new Date(now.replace(/\\-/g, \"\\/\"));\r\n");
      out.write("\t  if(d1>d2){  \r\n");
      out.write("          $(\"#result1\").html(\"考勤日期不得晚于今天！\");\r\n");
      out.write("          $(\"#result1\").show();\r\n");
      out.write("           flg=false;\r\n");
      out.write("           return false;  \r\n");
      out.write("         }else{\r\n");
      out.write("           $(\"#result1\").hide();\r\n");
      out.write("           flg=true;\r\n");
      out.write("          } \r\n");
      out.write("\t}\r\n");
      out.write("    </script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("#head{\r\n");
      out.write("   margin-top:10px;\r\n");
      out.write("   margin-buttom:10px;\r\n");
      out.write("}\r\n");
      out.write(".l-table-edit-td {\r\n");
      out.write("\tpadding: 4px;\r\n");
      out.write("}\r\n");
      out.write(".s {\r\n");
      out.write("\twidth: 61px;\r\n");
      out.write("\theight: 18px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tbackground-color: #eeeeee;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write(".l-button-submit,.l-button-test {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\tpadding-bottom: 2px;\r\n");
      out.write("}\r\n");
      out.write(".l-verify-tip {\r\n");
      out.write("\tleft: 230px;\r\n");
      out.write("\ttop: 120px;\r\n");
      out.write("}\r\n");
      out.write(".link{\r\n");
      out.write("width:160px;height:25px;background: #fefefe;border: 1px solid #bbb;font-size: 14px;color: #333;border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("#result{\r\n");
      out.write(" color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body style=\"padding: 2px\">\r\n");
      out.write("\t<div id=\"head\">\r\n");
      out.write("\t\t  <table cellpadding=\"0\" cellspacing=\"0\" class=\"l-table-edit\" >\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\" class=\"l-table-edit-td\">时间:</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\"><input  id=\"date\" onchange=\"check()\" ltype=\"text\" type=\"text\" class=\"date_picker link\"></td>\r\n");
      out.write("\t\t\t    <td align=\"right\" class=\"l-table-edit-td\">节次:</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t  <select id=\"time\" name=\"time\" class=\"link\"   >\r\n");
      out.write("\t\t\t\t    <option value=\"8:20-10:00\">第一大节</option>\t\t\t\t  \r\n");
      out.write("\t\t\t\t    <option value=\"10:20-12:00\">第二大节</option>\r\n");
      out.write("\t\t\t\t    <option value=\"14:00-15:40\">第三大节</option>\r\n");
      out.write("\t\t\t\t    <option value=\"16:00-17:40\">第四大节</option>\r\n");
      out.write("\t\t\t\t    <option value=\"18:30-20:10\">第五大节</option>\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td align=\"right\" class=\"l-table-edit-td\"><!-- 课程: --><input id=\"courseid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.num }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"hidden\"/></td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">");
      out.write("</td>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t  <th colspan=\"6\"><div id=\"result\"></div><div id=\"result1\" style=\"color: red;\" ></div></th>\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a class=\"l-button\" style=\"width:70px;float:left; margin:3px;\" onclick=\"attendence()\">出&nbsp;&nbsp;勤</a>\r\n");
      out.write("\t\t<a class=\"l-button\" style=\"width:70px;float:left; margin:3px;\" onclick=\"late()\">迟&nbsp;&nbsp;到</a>\r\n");
      out.write("\t\t<a class=\"l-button\" style=\"width:70px;float:left; margin:3px;\" onclick=\"leaveearly()\">早&nbsp;&nbsp;退</a>\r\n");
      out.write("\t\t<a class=\"l-button\" style=\"width:70px;float:left; margin:3px;\" onclick=\"notarrival()\">旷&nbsp;&nbsp;课</a>\r\n");
      out.write("\t\t<div class=\"l-clear\"></div>\r\n");
      out.write("\t\t<div id=\"maingrid\" ></div>\r\n");
      out.write("\t\t<div  style=\"display:none;\">\r\n");
      out.write("</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
