package org.apache.jsp.WEB_002dINF.course;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.springframework.web.context.request.SessionScope;
import java.util.*;

public final class courselist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">   \r\n");
      out.write("    <title>天津工业大学国际教育学院教学服务系统</title>\t   \r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("js/ligerUI/skins/Aqua/css/ligerui-all.css\" rel=\"stylesheet\"type=\"text/css\" />\t\r\n");
      out.write("\t<link href=\"");
      out.print(basePath );
      out.write("js/ligerUI/skins/Gray/css/all.css\" rel=\"stylesheet\" type=\"text/css\"/>\t\r\n");
      out.write("     <link href=\"js/ligerUI/skins/ligerui-icons.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-validation/jquery.validate.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/json2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"js/jquery/jquery-1.3.2.min.js\"type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"js/ligerUI/core/base.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"js/ligerUI/ligerui.all.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"js/ligerUI/plugins/ligerToolBar.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">  \r\n");
      out.write("   $(f_initGrid);\r\n");
      out.write("\tvar manager, g;\r\n");
      out.write("\tfunction f_initGrid() {\r\n");
      out.write("\t\tg = manager = $(\"#maingrid\").ligerGrid(\r\n");
      out.write("\t\t\t\t{\t\t\t\r\n");
      out.write("\t\t\t\tcolumns : [{\r\n");
      out.write("\t\t\t\tdisplay : 'ID',\r\n");
      out.write("\t\t\t\tname : 'id',\r\n");
      out.write("\t\t\t\twidth : 60,\r\n");
      out.write("\t\t\t\thide:true,\r\n");
      out.write("\t\t\t\ttype : 'int'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tdisplay : '课程编号',\r\n");
      out.write("\t\t\t\tname : 'num',\r\n");
      out.write("\t\t\t\tminWidth : 120,\r\n");
      out.write("\t\t\t\teditor: { type: 'text'}\r\n");
      out.write("\t\t\t} , {\r\n");
      out.write("\t\t\t\tdisplay : '课程名称',\r\n");
      out.write("\t\t\t\tname : 'coursename',\r\n");
      out.write("\t\t\t\tminWidth : 120,\r\n");
      out.write("\t\t\t\teditor: { type: 'text'}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tdisplay : '课程名称（英文）',\r\n");
      out.write("\t\t\t\tname : 'coursename_en',\r\n");
      out.write("\t\t\t\tminWidth : 120,\r\n");
      out.write("\t\t\t\teditor: { type: 'text'}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tdisplay : '开课周数',columns:[\r\n");
      out.write("\t\t\t\t{ display:'起始周' , name:'beginweeks',minWidth : 60,editor: { type: 'int'} },\r\n");
      out.write("\t\t\t\t{ display:'结束周' , name:'endweeks',  minWidth : 60,editor: { type: 'int'} }\r\n");
      out.write("\t\t\t\t]\t\t\t\r\n");
      out.write("\t\t\t} , {\r\n");
      out.write("\t\t\t\tdisplay : '学分',\r\n");
      out.write("\t\t\t\tname : 'credits',\r\n");
      out.write("\t\t\t\tminWidth : 60\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tdisplay : '学时',columns:[\r\n");
      out.write("\t\t\t\t{ display:'周学时' , name:'weeklesson',minWidth : 60,editor: { type: 'int'} },\r\n");
      out.write("\t\t\t\t{ display:'总学时' , name:'lessoncount',  minWidth : 60,editor: { type: 'int'} }\r\n");
      out.write("\t\t\t\t]\t\t\t\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tdisplay : '课程性质',\r\n");
      out.write("\t\t\t\tname : 'character',\r\n");
      out.write("\t\t\t\tminWidth : 120\t\t\t\r\n");
      out.write("\t\t\t} /* , {\r\n");
      out.write("\t\t\t\tdisplay : '考核方式',\r\n");
      out.write("\t\t\t\tname : 'checkway',\r\n");
      out.write("\t\t\t\tminWidth : 120,\r\n");
      out.write("\t\t\t\teditor: { type: 'select', data: CourseCheckway, valueColumnName: 'Coursecheckway', displayColumnName: 'Coursecheckway' }, \r\n");
      out.write("                  render: function (item)\r\n");
      out.write("                    {\r\n");
      out.write("                        for (var i = 0; i < CourseCheckway.length; i++)\r\n");
      out.write("                        {\r\n");
      out.write("                            if (CourseCheckway[i]['Coursecheckway'] == item.checkway)\r\n");
      out.write("                                return CourseCheckway[i]['Coursecheckway'];\r\n");
      out.write("                        }\r\n");
      out.write("                        return item.Coursecheckway;\r\n");
      out.write("                    } \r\n");
      out.write("\t\t\t}  */, {\r\n");
      out.write("\t\t\t\tdisplay : '开课学院',\r\n");
      out.write("\t\t\t\tname : 'academic',\r\n");
      out.write("\t\t\t\tminWidth : 120\t\t\t\t\r\n");
      out.write("\t\t\t} , {\r\n");
      out.write("\t\t\t\tdisplay : '负责教师',\r\n");
      out.write("\t\t\t\tname : 'teacher',\r\n");
      out.write("\t\t\t\twidth : 120,\r\n");
      out.write("\t\t\t\teditor: { type: 'text'}\r\n");
      out.write("\t\t\t}  , {\r\n");
      out.write("\t\t\t\tdisplay : '状态',\r\n");
      out.write("\t\t\t\tname : 'isDeleted',\r\n");
      out.write("\t\t\t\twidth : 120,\r\n");
      out.write("\t\t\t\teditor: { type: 'text'},\r\n");
      out.write("\t\t\t\trender:function (item) {\r\n");
      out.write("\t\t\t\t\tif (parseInt(item.isDeleted) == 1) {\r\n");
      out.write("\t\t\t\t\t\treturn \"<font style='color:red'>不可用</font>\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\treturn \"<font style='color:green'>正常</font>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\t\t\tonSelectRow : function(rowdata, rowindex) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#txtrowindex\").val(rowindex);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tenabledEdit : true,\r\n");
      out.write("\t\t\t\t\tclickToEdit : false,\r\n");
      out.write("\t\t\t\t\tisScroll : false,\r\n");
      out.write("\t\t\t\t\tcheckbox:false,\r\n");
      out.write("\t\t\t        rownumbers:true,\r\n");
      out.write("\t\t\t        pageSize:15,\r\n");
      out.write("\t\t\t\t\turl :'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courselist.action',\r\n");
      out.write("\t\t\t\t\twidth : '100%',\r\n");
      out.write("\t\t\t\t\ttoolbar: { items: [{ text: '添加',click: add,  icon: 'add' },\r\n");
      out.write("\t\t\t\t\t                   { text: '修改',click: beginEdit,  icon: 'edit' },\r\n");
      out.write("\t\t\t\t\t                   { text: '删除',click: deleterow,  icon: 'delete' },\r\n");
      out.write("\t\t\t\t\t                   { text: '恢复',click: recoveryrow,  icon: 'save' },\r\n");
      out.write("\t\t\t\t\t                   { text: '批量添加', click: batchAdd, icon:'add'}\r\n");
      out.write("\t\t\t\t\t                   ]}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction batchAdd(){\r\n");
      out.write("\t\tvar str = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_jmpLoadTxt.action\";\r\n");
      out.write("\t\tm=$.ligerDialog.open({\t\t   \r\n");
      out.write("\t\t\turl : str,\r\n");
      out.write("\t\t\theight : 400,\r\n");
      out.write("\t\t\twidth : 800,\r\n");
      out.write("\t\t\tisResize : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar m;\r\n");
      out.write("   function beginEdit() {\r\n");
      out.write("      var row = manager.getSelectedRow();\r\n");
      out.write("      if (!row) { alert('请选择一个课程！'); return; }\r\n");
      out.write("      var str = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courseedit.action?course.id=\"+ row.id\r\n");
      out.write("\t\t\t\t/* +\"&course.num=\"+encodeURI(encodeURI(row.num))\r\n");
      out.write("\t\t\t\t+\"&course.coursename=\"+encodeURI(encodeURI(row.coursename))\r\n");
      out.write("\t\t\t\t+\"&course.beginweeks=\"+encodeURI(encodeURI(row.beginweeks))\r\n");
      out.write("\t\t\t\t+\"&course.endweeks=\"+encodeURI(encodeURI(row.endweeks))\r\n");
      out.write("\t\t\t    //+\"&course.credits=\"+row.credits\r\n");
      out.write("\t\t\t  \t+\"&course.character=\"+encodeURI(encodeURI(row.character))\r\n");
      out.write("\t\t\t    +\"&course.checkway=\"+encodeURI(encodeURI(row.checkway))\r\n");
      out.write("\t\t\t\t+\"&course.teacher=\"+encodeURI(encodeURI(row.teacher)) */;\r\n");
      out.write("\t  m=$.ligerDialog.open({\r\n");
      out.write("\t\t\turl : str,\r\n");
      out.write("\t\t\theight : 450,\r\n");
      out.write("\t\t\twidth : 430,\r\n");
      out.write("\t\t\ttitle:'更新课程',\r\n");
      out.write("\t\t\tisDrag:true,\r\n");
      out.write("\t\t\tisResize : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvar m;\r\n");
      out.write("    function add(){\r\n");
      out.write("\tvar str = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_coursebeginadd.action\";\t\r\n");
      out.write("\t\tm=$.ligerDialog.open({\r\n");
      out.write("\t\t\turl : str,\r\n");
      out.write("\t\t\theight : 540,\r\n");
      out.write("\t\t\twidth : 430,\r\n");
      out.write("\t\t\tisDrag:true,\r\n");
      out.write("\t\t\tshowMax:true,\r\n");
      out.write("\t\t\tshowToggle:true,\r\n");
      out.write("\t\t\tslide: false,\t\t\t\r\n");
      out.write("\t\t\tmodal:false,\r\n");
      out.write("\t\t\tleft:200,\r\n");
      out.write("\t\t\ttitle:'添加课程',\r\n");
      out.write("\t\t\tallowClose:true,\r\n");
      out.write("\t\t    isResize : false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t //window.open(str,'toolbar=no,scrollbars=yes,resizable=no,top=0,left=0,width=400,height=300');\r\n");
      out.write("\t   //window.open (str, 'newwindow', 'height=450, width=300, top=200, left=400, toolbar=no, menubar=no, scrollbars=no, resizable=no,location=n o, status=no');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleterow() {\r\n");
      out.write("\tvar row = manager.getSelectedRow();\r\n");
      out.write("\t\tif (!row) {\r\n");
      out.write("\t\t\talert('请选择课程！');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t$.ligerDialog.confirm(\"是否删除？第一次删除将会使该课程不可用。如果没有成绩或记录与此课程关联，第二次删除会彻底清除记录，否则不做任何操作。\", function (yes){\r\n");
      out.write("         if(yes){\r\n");
      out.write("            $.ligerDialog.prompt('请输入确认密码', function (yes, value){\r\n");
      out.write("               if (yes){\r\n");
      out.write("                //验证密码\r\n");
      out.write("                  var userid = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("                  $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/User_pwdcheck.action?user.id=\"+ userid\r\n");
      out.write("\t\t            +\"&user.password=\"+value , null, function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"fail\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"输入的密码不正确!\");\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tvar rows = g.getCheckedRows();\r\n");
      out.write("                        var str = \"\";\r\n");
      out.write("                        $(rows).each(function (){ str += this.id; });\r\n");
      out.write("\t                    /* $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_coursedelete.action?ids=\"+ str); */\r\n");
      out.write("\t\t\t            $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_coursedelete.action?ids=\"+str,null,function(){\r\n");
      out.write("\t\t\t             //manager.deleteSelectedRow();\r\n");
      out.write("\t\t\t            //window.location.reload();\r\n");
      out.write("\t\t\t            g.loadData();\r\n");
      out.write("\t\t\t            });\r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t   });\t\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\t\t\t\t\t\t\t\t\t\t\t\t\t\t          \r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\tfunction fuzzy () {\r\n");
      out.write("\t\tvar t = $(\"#searchText\").val();\r\n");
      out.write("\t\t$(\"#maingrid\").ligerGrid({\r\n");
      out.write("\t\t  url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courseFuzzy.action?fuzzyText=\" + encodeURI(encodeURI(t))\r\n");
      out.write("\t\t  \t+ \"&queryType=\" + $(\"#coursecharacter\").val() \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction recoveryrow(){\r\n");
      out.write("\t  var row = g.getSelectedRow();\r\n");
      out.write("\t  if(!row){alert(\"请先选择一项！\");return;}\r\n");
      out.write("\t  if(row.isDeleted==0){\r\n");
      out.write("\t     //alert(\"该课程未被删除，无需恢复！\");\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t     $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courserecovery.action?course.id=\"+row.id,null,function(){\r\n");
      out.write("\t       //alert(\"该课程已恢复！\");\r\n");
      out.write("\t       //window.location.reload();\r\n");
      out.write("\t       g.loadData();\r\n");
      out.write("\t     })\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("/* \tfunction f_search(){\r\n");
      out.write("\t  var coursename = $(\"#coursename\").val();\r\n");
      out.write("\t  var num = $(\"#num\").val();\r\n");
      out.write("\t  var character = $(\"#coursecharacter\").val();\r\n");
      out.write("\t  if(coursename.length==0&&num.length==0&&character.length==0){\r\n");
      out.write("\t    $(\"#maingrid\").ligerGrid({\r\n");
      out.write("\t\t  url:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courselist.action'\r\n");
      out.write("\t\t})\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t    var str = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_coursesearch.action?course.coursename=\"+encodeURI(encodeURI(coursename))\r\n");
      out.write("\t    +\"&course.num=\"+encodeURI(encodeURI(num))\r\n");
      out.write("\t    +\"&course.character=\"+encodeURI(encodeURI(character));\r\n");
      out.write("\t    $(\"#maingrid\").ligerGrid({\r\n");
      out.write("\t\t  url:str\r\n");
      out.write("\t\t})\r\n");
      out.write("\t    \r\n");
      out.write("\t  }\r\n");
      out.write("\t} */\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#head{\r\n");
      out.write(" width: 99%;\r\n");
      out.write(" height:80px;\r\n");
      out.write(" margin:auto;\r\n");
      out.write(" border:4px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write(" float: left;\r\n");
      out.write(" height: 100%;\r\n");
      out.write(" width: 10%;\r\n");
      out.write(" text-aligncenter;\r\n");
      out.write(" border-right:2px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write(".search{\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write(".l-table-edit{\r\n");
      out.write(" height:90px;\r\n");
      out.write(" align:center;\r\n");
      out.write(" width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".search.l-table-edit td{\r\n");
      out.write("  border-bottom: 1px solid #c6c6c6 ;\r\n");
      out.write("}\r\n");
      out.write(".link{\r\n");
      out.write("width:160px;height:25px;background: #fefefe;border: 1px solid #bbb;font-size: 14px;color: #333;border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write(".l-button{\r\n");
      out.write(" width:70px;float:left; margin:15px 160px 5px ;\r\n");
      out.write(" border-radiux:5px;\r\n");
      out.write("}\r\n");
      out.write(".l-dialog{\r\n");
      out.write("  width:300px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body style=\"padding: 2px\">\t\t\r\n");
      out.write("\t\t<div id=\"head\">\r\n");
      out.write("\t      <div class=\"search\" >\r\n");
      out.write("\t         <table cellpadding=\"0\" cellspacing=\"0\" class=\"l-table-edit\" width=\"100%\" >\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\" class=\"l-table-edit-td\" width=\"100px\" >&nbsp;&nbsp;关键字:&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t  <input id=\"searchText\" class=\"link\" onkeyup=\"fuzzy()\" name=\"searchText\" />\r\n");
      out.write("\t\t\t\t</td>\t\t\r\n");
      out.write("\t\t\t   <td align=\"right\" class=\"l-table-edit-td\">&nbsp;&nbsp;&nbsp;课程性质:&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t   <select id=\"coursecharacter\" name=\"coursecharacter\" onchange=\"fuzzy()\" class=\"link\" >\r\n");
      out.write("\t\t\t\t      <option value=\"-1\" ></option>\r\n");
      out.write("\t\t\t\t      <option value=\"0\" >必修</option>\r\n");
      out.write("\t\t\t\t      <option value=\"1\" >限选</option>\r\n");
      out.write("\t\t\t\t      <option value=\"2\" >任选</option>\t\t\t\t \r\n");
      out.write("\t\t\t\t   </select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<!-- <td align=\"right\" class=\"l-table-edit-td\"><a class=\"l-button\" onclick=\"fuzzy()\"><strong>查&nbsp;&nbsp;询</strong></a></td> -->\t\r\n");
      out.write("\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!-- <a class=\"l-button\" onclick=\"f_search()\"><strong>查&nbsp;&nbsp;询</strong></a> -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\t\t\r\n");
      out.write("\t\t<div class=\"l-clear\"></div>\r\n");
      out.write("\t\t<div id=\"maingrid\" ></div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
