package org.apache.jsp.WEB_002dINF.course;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.tjpu.bean.Syllabus;
import com.opensymphony.xwork2.ActionContext;

public final class newCourseAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("js/jquery/jquery-1.6.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <link href=\"");
      out.print(basePath);
      out.write("js/ligerUI/skins/Aqua/css/ligerui-all.css\" rel=\"stylesheet\"type=\"text/css\" />\t\r\n");
      out.write("\t<link href=\"");
      out.print(basePath );
      out.write("js/ligerUI/skins/Gray/css/all.css\" rel=\"stylesheet\" type=\"text/css\"/>\t\r\n");
      out.write("    <link href=\"");
      out.print(basePath);
      out.write("css/date.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("js/ligerUI/core/base.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(basePath);
      out.write("js/ligerUI/plugins/ligerDateEditor.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.date_input.pack.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("js/ligerUI/skins/Gray/css/form.css\"rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("js/ligerUI/skins/Gray/css/common.css\"rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("css/date.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-table-edit {\r\n");
      out.write("\tmargin-left: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-table-edit-td {\r\n");
      out.write("\tpadding: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-button-submit,.l-button-test {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\tpadding-bottom: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-verify-tip {\r\n");
      out.write("\tleft: 230px;\r\n");
      out.write("\ttop: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#errorLabelContainer {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tborder: 1px solid #FF4466;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #FFEEEE;\r\n");
      out.write("\tcolor: Red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link {\r\n");
      out.write("\twidth: 170px;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\tbackground: #fefefe;\r\n");
      out.write("\tborder: 1px solid #bbb;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("/* .date_selector .month_nav{float: left;width: 40%;}\r\n");
      out.write(".date_selector .year_nav{float: right;width: 35%;margin-right: 60px;} */\r\n");
      out.write("textarea {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <script type=\"text/javascript\">\t\r\n");
      out.write("\t\tfunction uniqueChk (){\r\n");
      out.write("\t\t\tvar num = $(\"#number\").val();\r\n");
      out.write("\t\t\tvar name = $(\"#name\").val();\t\t\t\r\n");
      out.write("\t\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courseUniqueChk.action?course.coursename=\"\r\n");
      out.write("\t\t\t\t\t    + encodeURI(encodeURI(name))\r\n");
      out.write("\t\t\t\t\t\t+ \"&course.num=\" + num;\r\n");
      out.write("\t\t\t$.ajax({  \r\n");
      out.write("\t\t        type : \"POST\",  \r\n");
      out.write("\t\t        url : url,\r\n");
      out.write("\t\t        dataType : \"JSON\", \r\n");
      out.write("\t\t        error: function (){\r\n");
      out.write("\t\t        \talert(\"数据传输错误，请联系管理员！\");\r\n");
      out.write("\t\t        \treturn false;\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        success : function(data) {\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \tif (data.length > 0){ \r\n");
      out.write("\t\t        \t\t//alert(\"not pass\");\r\n");
      out.write("\t\t        \t\treturn false;\r\n");
      out.write("\t\t        \t} else {\t   \r\n");
      out.write("\t\t        \t\t//alert(\"pass\");    \t\t\r\n");
      out.write("\t\t        \t\treturn true;\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t\t        }  \r\n");
      out.write("\t\t    }); \t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction clear(){\r\n");
      out.write("\t\t\t$(\"#msg\").text(\" \");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction err (msg){\r\n");
      out.write("\t\t\t$(\"#msg\").text(msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction submit(){\r\n");
      out.write("\t\t\tvar number = $(\"#number\");\r\n");
      out.write(" \t\t\tvar name = $(\"#name\");\r\n");
      out.write(" \t\t\tvar beginweek = $(\"#beginweek\");\r\n");
      out.write(" \t\t\tvar endweek = $(\"#endweek\");\r\n");
      out.write(" \t\t\tvar credit = $(\"#credit\");\r\n");
      out.write(" \t\t\tvar weeklesson = $(\"#weeklesson\");\r\n");
      out.write(" \t\t\tvar character = $(\"#character\");\r\n");
      out.write(" \t\t\tvar college = $(\"#college\");\r\n");
      out.write(" \t\t\tvar teacher = $(\"#teacher\");\r\n");
      out.write(" \t\t\tvar nameEN = $(\"#nameEN\");\r\n");
      out.write(" \t\t\tclear();\r\n");
      out.write("\t\t\t/* if (!validate_required(number,\"课程编号不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar reg1 = /^[1-9][0-9]{7}$/;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (!reg1.test(number.val())){\r\n");
      out.write("\t\t\t\terr(\"课程编号只能为8位数字\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (!validate_required(name,\"课程名不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//var reg = /^(?![0-9])[a-zA-Z0-9_\\u4e00-\\u9fa5]{2,}$/;\r\n");
      out.write("\t\t\tvar reg = /^\\S{2,}$/;\r\n");
      out.write("\t\t\tif(!reg.test(name.val())){\r\n");
      out.write("\t\t\t\terr(\"课程名由2个以上的中英文字符组成\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//alert(\"here\");\r\n");
      out.write("\t\t\tvar regx = /^[a-zA-Z]{2,}$/;\r\n");
      out.write("\t\t\t//alert($(\"#nameEN\").val());\r\n");
      out.write("\t\t\tif (!validate_required(nameEN, \"课程英文名不能为空\")) {\r\n");
      out.write("\t\t\t\treturn;\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (!regx.test(nameEN.val())) {\r\n");
      out.write("\t\t\t\terr (\"课程英文名应由2个或以上英文字符构成\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* var url1 = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courseUniqueChk.action?course.coursename=\"\r\n");
      out.write("\t\t\t\t\t    + encodeURI(encodeURI(name.val()))\r\n");
      out.write("\t\t\t\t\t\t+ \"&course.num=\" + number.val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({  \r\n");
      out.write("\t\t        type : \"POST\",  \r\n");
      out.write("\t\t        url : url1,\r\n");
      out.write("\t\t        dataType : \"JSON\", \r\n");
      out.write("\t\t        error: function (){\r\n");
      out.write("\t\t        \terr(\"课程编号不能与之前的课程重复\");\r\n");
      out.write("\t\t        \treturn;\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        success : function(data) {\r\n");
      out.write("\t\t        \tif (data.length > 0){ \r\n");
      out.write("\t\t        \t\terr(\"课程编号不能与之前的课程重复\");\r\n");
      out.write("\t\t        \t\treturn;\r\n");
      out.write("\t\t        \t} else { */\r\n");
      out.write("\t\t        \t\t//alert(\"pass\");\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t\tif (!validate_required(beginweek,\"起始周不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar reg2 = /^[0-9]+$/;\r\n");
      out.write("\t\t\tif (!reg2.test(beginweek.val())) {\r\n");
      out.write("\t\t\t\terr(\"起始周只能是数字\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (!validate_required(endweek,\"结束周不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar reg3 = /^[0-9]{1,2}$/;\r\n");
      out.write("\t\t\tif (!reg3.test(endweek.val())){\r\n");
      out.write("\t\t\t\terr(\"结束周只能是数字\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(parseInt(endweek.val()) > 21){\r\n");
      out.write("\t\t\t\terr(\"结束周不能晚于21周\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar start = parseInt(beginweek.val());\r\n");
      out.write("\t\t\tvar end = parseInt(endweek.val());\r\n");
      out.write("\t\t\tif (start > end){\r\n");
      out.write("\t\t\t\terr(\"结束周不能早于起始周\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (!validate_required(credit,\"学分不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (!validate_required(weeklesson,\"周学时不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (!validate_required(character,\"课程类型不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (!validate_required(college,\"开设学院不能为空\")){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar teacher = $(\"#teacher\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(teacher != \"\"){\r\n");
      out.write("\t\t\t\tvar regg = /^[a-zA-Z\\s\\u4e00-\\u9fa5]{2,}$/;\r\n");
      out.write("\t\t\t\tif (!regg.test(teacher)){\r\n");
      out.write("\t\t\t\t\terr(\"教师姓名只能由2个以上的中英文组成\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/system/Class_courseendadd.action?course.coursename=\"\r\n");
      out.write("\t\t\t\t+  encodeURI(encodeURI($(\"#name\").val()))\r\n");
      out.write("\t\t        +\"&course.teacher=\"+  encodeURI(encodeURI($(\"#teacher\").val()))\r\n");
      out.write("\t\t        +\"&course.character=\"+  encodeURI(encodeURI($(\"#character\").val()))\r\n");
      out.write("\t\t        +\"&course.beginweeks=\"+ $(\"#beginweek\").val()\r\n");
      out.write("\t\t        +\"&course.endweeks=\"+ $(\"#endweek\").val()\r\n");
      out.write("\t\t        +\"&course.credits=\"+ $(\"#credit\").val()\r\n");
      out.write("\t\t        +\"&course.weeklesson=\"+ $(\"#weeklesson\").val()\r\n");
      out.write("\t\t        +\"&course.academic=\"+ encodeURI(encodeURI($(\"#college\").val()))\r\n");
      out.write("\t\t        /* +\"&course.num=\"+  encodeURI(encodeURI($(\"#number\").val())) */\r\n");
      out.write("\t\t        +\"&course.coursename_en=\" + nameEN.val();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//alert(nameEN.val());\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$.post(url,null,function(){\r\n");
      out.write("    \t\t    parent.window.location.reload();\r\n");
      out.write("    \t\t    window.close(); \r\n");
      out.write("\t        });\r\n");
      out.write("\t\t     /*    \t}\r\n");
      out.write("\t\t        }  \r\n");
      out.write("\t\t    });  */\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction validate_required(ids,alerttxt)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif (ids.val() == null || ids.val() == \"\"){\r\n");
      out.write("\t\t\t\t$(\"#msg\").text(alerttxt);\r\n");
      out.write("\t\t\t\tids.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("    <table cellpadding=\"0\" cellspacing=\"0\" class=\"l-table-edit\" >\r\n");
      out.write("    \t<!-- <tr style=\"font-size:12px\">\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">课程编号<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"link\" onchange=\"clear()\" id=\"number\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("    \t</tr> -->\r\n");
      out.write("    \t<tr style=\"font-size:12px\">\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">课程名<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"link\" id=\"name\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr style=\"font-size:12px\">\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">课程名(英文)<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"link\" id=\"nameEN\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr style=\"font-size:12px\">\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">起始周<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"link\"  id=\"beginweek\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr style=\"font-size:12px\">\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">结束周<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"link\" id=\"endweek\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr style=\"font-size:12px\">\r\n");
      out.write("\t\t\t<td align=\"center\" class=\"l-table-edit-td\">学分<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t\t<select id=\"credit\" class=\"link\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0.5\">0.5</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1.5\">1.5</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\"font-size:12px\">\r\n");
      out.write("\t\t\t<td align=\"center\" class=\"l-table-edit-td\">周课时<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t\t<select id=\"weeklesson\" class=\"link\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\"font-size:12px\">\r\n");
      out.write("\t\t\t<td align=\"center\" class=\"l-table-edit-td\">课程性质<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t\t<select id=\"character\" class=\"link\" >\r\n");
      out.write("\t\t\t\t    <option value=\"必修\">必修</option>\r\n");
      out.write("\t\t\t\t    <option value=\"限选\">限选</option>\r\n");
      out.write("\t\t\t\t    <option value=\"任选\">任选</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\"font-size:12px\">\r\n");
      out.write("\t\t\t<td align=\"center\" class=\"l-table-edit-td\">开设学院<font style=\"color:red; font-size:20\">*</font></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\" >\r\n");
      out.write("\t\t\t\t <select id=\"college\"  class=\"link\" onchange=\"clear()\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"国际教育学院 \"  >国际教育学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"纺织学院\">纺织学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"材料科学与工程学院\">材料科学与工程学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"环境与化学工程学院\">环境与化学工程学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"机械工程学院\">机械工程学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"计算机科学与软件学院\">计算机科学与软件学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"电气工程与自动化学院 \">电气工程与自动化学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"电子与信息工程学院 \">电子与信息工程学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"理学院\">理学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"艺术与服装学院\">艺术与服装学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"管理学院 \">管理学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"经济学院\">经济学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"人文与法学院\">人文与法学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"外国语学院 \">外国语学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"马克思主义学院\">马克思主义学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"应用技术学院\">应用技术学院</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"继续教育学院\">继续教育学院</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\"font-size:12px\">\r\n");
      out.write("\t\t\t<td align=\"center\" class=\"l-table-edit-td\">负责教师</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\" >\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"link\" id=\"teacher\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\"font-size:12px\">\r\n");
      out.write("\t\t\t<td align=\"center\" class=\"l-table-edit-td\"></td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"提&nbsp;交\" id=\"Button1\" \r\n");
      out.write("\t\t\t\t\t\tonclick=\"submit()\" class=\"l-button l-button-submit\" />\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("    \t\t<td align=\"left\"></td>\r\n");
      out.write("\t\t\t\t<!-- <td align=\"right\" class=\"l-table-edit-td\"></td>\r\n");
      out.write("\t\t\t\t<td align=\"right\" class=\"l-table-edit-td\"></td>\r\n");
      out.write("\t\t\t\t<td align=\"left\" class=\"l-table-edit-td\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"申&nbsp;&nbsp;请\" id=\"Button1\" \r\n");
      out.write("\t\t\t\t\t\tonclick=\"tosubmit()\" class=\"l-button l-button-submit\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t<td align=\"left\"> -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <table style=\"font-size:14px; margin-left: 10px;\">\r\n");
      out.write("   \t\t<tr>\r\n");
      out.write("   \t\t\t<p id=\"msg\" style=\"color:red\"></p>\r\n");
      out.write("   \t\t</tr> \r\n");
      out.write("    </table>\r\n");
      out.write("  </body>\r\n");
      out.write("  \r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
